name: Refresh stakers

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/7 * * * *"
  push:
    branches:
      - master

jobs:
  refresh-stakers:
    name: trigger a re-download of stakers and their balances
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update stakers list
        run: yarn && yarn start
        env:
          NODE_URL: ${{ secrets.NODE_URL }}
          ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
          FARM_ADDRESS: "0xd41a21f6a3debfe28b06ace2312a69c53107cee5"
      - uses: actions/upload-artifact@v2
        with:
          name: stakers.json
          path: public/cache/stakers.json
